# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title TCRdist
#' @name TCRdist
#' @author Julian Spagnuolo
#' @description 
#'
#' @param 
#' @export
TCRdist <- function(TCRseq, CDR3) {
    .Call(`_TCRdist_TCRdist`, TCRseq, CDR3)
}

#' @title Vdist
#' @name Vdist
#' @author Julian Spagnuolo
#' @description compute pair-wise V distances using IMGT CDR1, CDR2 and CDR2.5 alignments
#'
#' @param 
#' @export
Vdist <- function(cdrs, Vgene, gap_penalty, weight) {
    .Call(`_TCRdist_Vdist`, cdrs, Vgene, gap_penalty, weight)
}

