# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title TCRdist
#' @name TCRdist
#' @author Julian Spagnuolo
#' @description 
#'
#' @param 
#' @export
cdrDist <- function(cdrx, cdry, cdr) {
    .Call('_TCRdist_cdrDist', PACKAGE = 'TCRdist', cdrx, cdry, cdr)
}

#' @title TCRdist
#' @name TCRdist
#' @author Julian Spagnuolo
#' @description 
#'
#' @param cdr1, matrix
#' @export
test <- function(cdrx, cdry) {
    .Call('_TCRdist_test', PACKAGE = 'TCRdist', cdrx, cdry)
}

